source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SKTimer_Example', :exclusive => true do
  pod 'SKTimer', :path => '../'
end

target 'SKTimer_Tests', :exclusive => true do
  pod 'SKTimer', :path => '../'

  
end
